### ISSUE TITLE
black screen after boot

### ISSUE THREAD

**Issue by darkmoon16** [prashantpaddune/Universal7885-P#4]
i build samsung M20 kernel but when i flash the boot.img the phone boots with display  and the phone works ( i receive calls ...etc)   but with a black screen ..please tell me how to fix it

**Comment by themagicalmammal** [comment]
how did you build the kernel

**Comment by darkmoon16** [comment]
> how did you build the kernel

i downloaded the source code
i downloaded the toolchain ( ubertc )
make mrproper
make clean
make m20lte_defconfig
and  make
i got the Image  and i used android image kitchen to rebuild  the boot.img

**Comment by darkmoon16** [comment]
any help plz

**Comment by prashantpaddune** [comment]
This kernel is only for Android Pie, also define toolchain path in cronos.sh and run the script to build this kernel . :)

**Comment by darkmoon16** [comment]
i used tw-8.1 branch

**Comment by prashantpaddune** [comment]
that branch is not for M20 devices, Its for testing purpose on A8/A8+

**Comment by darkmoon16** [comment]
alright ..i dont know from which source code you compiled the m20 quantum stock's kernel that i found in xda forums

**Comment by prashantpaddune** [comment]
https://github.com/prashantpaddune/universal7885/tree/m20lte
